# Generated by Django 2.2.23 on 2021-06-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0120_remove_contest_seen_by'),
        ('judge', '0119_hide_problem_authors'),
    ]

    operations = [
    ]
